name: projeto_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  uuid: ^4.5.1
  postgres: ^2.4.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.6.1
  jwt_decode: ^0.3.1
  collection: ^1.17.0



dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
